### ISSUE TITLE
Add more details when summarizing failed samples

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/proviral#7]
From Natalie's e-mail request:
* [x] Samples that have the NFLHIVDNA project code but no HIV BLAST matches should include all their contigs and conseqs in the contig and conseq analysis files, with whatever the current error code is (always "not hiv"?). If a sample has at least one HIV BLAST match, then any contigs and conseqs that don't match HIV will be ignored and not reported in those files. (They'll still be in the original output from MiCall, of course.)
* [x] In `output_summary.csv`, can columns E through O be populated with the appropriate information for sequences with a "primer error"? She's most interested in being able to retrieve the sequence (column H) easily.
* [x] Not strictly related to failed samples, but copy the `is_rev_comp` column from contig or conseq analysis file to the outcome summary file.
* [ ] Accept a few missing bases at the start of the primer when searching the larger section of 200 bases. (See comment below.)
* [ ] Increase larger section to 250 bases.

**Comment by nkinloch2** [comment]
From (virtual) meeting (14-April-2021) in response to Natalie's email:

**Action items:**

1) (as above) NFLHIVDNA samples with no HIV BLAST results to have their conitgs/conseqs reported in those files with the error code 'not hiv', where if a sample has at least one HIV BLAST result everything non-hiv can be ignored
-Don may come back to Natalie on this regarding the error messages that could possibly be generated for these samples (could any message other than 'not hiv' be reported?)

2) (as above) In 'outcome_summary.csv', samples with primer errors should have columns E through O populated with the appropriate information for the sequence

3) (as above) Add column to 'outcome_summary.csv' that indicates whether the sequence was reverse complemented where this info can be copied from the relevant conseq/contig file

4) Stringency of search for complete primer in primer validation step:
(fwd primer as a descriptive example): Currently, the pipeline searches for the complete fwd primer in the first 50 base of the sequence and, if it is not found, iteratively shortens the primer from its 5' end (HXB2 space), searching for this shorter sequence (up until and including only 7 bases remain of the original primer sequence) to validate the presence of the primer. If the complete primer is not found, the pipeline also searches for the complete primer in the first 200 bases of sequences (from 5' end in HXB2 space), where, currently, if the complete primer is not found, the pipeline reverts back to reporting results on the outcome of the search in the first 50 bases.
To be changed: 
(fwd primer search) allow 'complete primer pass' in the 200 base search for primer sequences that are up to and including 3 bases shorter at the 5' end (HXB2 space) than the complete primer sequence.
(rev primer search) allow 'complete primer pass' in the 200 base search for primer sequences that are up to and including 3 bases shorter at the 3' end (HXB2 space) than the complete primer sequence.
otherwise report results for 50-base search (as current)

5) For accommodate instances of repeated primer sequences (which are in some cases partial), expand the secondary primer validation search window to 250 bases at the relevant end of the sample sequence

**Items to keep on our radar:**

1) Currently, in cases of 'ambiguous primer validation' (n bases primer recovered 6<=n <=1), the portion of the primer sequence that overlaps the sample sequence and the following 25 bases are aligned to HXB2 where if the alignment produces no gaps characters, the alignment passes and the presence of the primer is considered validated. However, one cases of a v. poor alignment passing was discovered. We debated the possibility of changing the 'no gaps' criteria to a levenshtein distance criteria but were unsure what the cut off value would be for this and also concerned about potential knock-on effects that could introduce a bunch of new issues with the pipeline. Decision was to keep this on our radar now and see how often the issue crops up.
